config/routes.rb
Rails.application.routes.draw do
root 'songs#index' # 追加：ルートへのルーティングを追加
  #get 'artists/index'

  #get 'artists/show'

resources :artists, only: [:index, :show]
  
  match '/songs',  to: 'songs#index', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :song_artists
  has_many :songs, through: :song_artists
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :song_artists
  has_many :artists, through: :song_artists
end

app/models/song_artist.rb
class SongArtist < ApplicationRecord
  belongs_to :song
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :navbar_ransack

  def index
  	@artists = Artist.page(params[:page])
  end

  def show
  	@artist = Artist.find(params[:id])
  end

  private
  def navbar_ransack
    @q = Song.ransack(params[:q])
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  	@q = Song.ransack(params[:q])
    @songs = @q.result.page(params[:page])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Songs</th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.name, artist_path(artist) %></td>
      <td><%= artist.songs.size %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @artists %>

app/views/artists/show.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Display artist</th>
      <th>ranking</th>
      <th>year</th>
    </tr>
  </thead>
  <tbody>
    <% @artist.songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>
      <td><%= song.display_artist %></td>
      <td><%= song.ranking %></td>
      <td><%= song.year %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
 <div class="navbar navbar-default navbar-fixed-top">
   <div class="container">
    <div class="navbar-header">
      <%= link_to 'Billboard', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Artist', artists_path %></li>
      </ul>
     <%= search_form_for @q, html: { class: 'navbar-form navbar-left' } do |f| %>
      <div class="form-group">
        <%= f.search_field :title_cont, class: 'form-control', placeholder: 'タイトル' %>
      </div>
      <div class="form-group">
        <%= f.search_field :display_artist_cont, class: 'form-control', placeholder: 'display_artist' %>
      </div>
      <%= f.submit class: 'btn btn-default' %>
     <% end %>
   </div>
  </div>
 </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/songs/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= sort_link(@q, :title) %></th>
      <th><%= sort_link(@q, :display_artist) %></th>
      <th><%= sort_link(@q, :ranking) %></th>
      <th><%= sort_link(@q, :year) %></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>
      <td>
        <% song.artists.each do |artist| %>
      <% song.display_artist.gsub!(/#{artist.name}/) {link_to artist.name, artist_path(artist)} %>
    <% end %>
    <%= song.display_artist.html_safe %>
      </td>
      <td><%= song.ranking %></td>
      <td><%= song.year %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @songs %>